meta:
  name:    ultimate-guide-to-bosh
  target:  sw
  url:     https://ci.starkandwayne.com

  cf:
    uri: https://api.run.pivotal.io
    organization: starkandwayne
    space-production: ultimate-guide-to-bosh
    username: (( vault "secret/pipelines/shared/cf/pws/starkandwayne:username" ))
    password: (( vault "secret/pipelines/shared/cf/pws/starkandwayne:password" ))

  github:
    owner: starkandwayne
    repo: ultimate-guide-to-bosh
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))
